# Generated by Django 3.1.6 on 2021-09-24 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user', 'no'], name='main_task_user_id_38a81f_idx'),
        ),
    ]
