# Generated by Django 3.1.6 on 2021-09-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210924_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='deadline',
        ),
        migrations.AddField(
            model_name='task',
            name='deadline_date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='deadline_time',
            field=models.TimeField(db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='taskrelation',
            constraint=models.UniqueConstraint(fields=('parent', 'child'), name='uq_task_parent_child'),
        ),
    ]
