# Generated by Django 3.1.6 on 2021-07-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210715_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_done',
        ),
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='done_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
